#!/bin/bash

#cd '/home/omniai/GarageRoof-alert-testing'
cd '/VideoLibrary/DITesting/1CIF-count-sampleDumpfiles/B1.1.0.5/tmp/'
#strip out the track ID and time stamps, remove last 6 characters from time stamps
awk -F ',' '{print $1, $2}' 1CIF-cated.csv > ztrackTimes
awk '{print $1}' ztrackTimes >zID
awk '{print $2}' ztrackTimes > zDates 
sed -i 's/.\{6\}$//' zDates

#Convert the epoch time into human readable time
for i in `less zDates`; do
	printf '%(%F %T)T\n' >> zDates2
done

#Strip out the year-month-day and remove the white spaces
awk  '{print $1}'  zDates2  > zDates-day  # use for alerts per day
awk -F '-' '{print $2, $3}' zDates2 |  sed  's/.\{6\}$//' > zDates-hr #strips month day and hour use for alerts per hour

#paste ID and Dates2 back together, sort them by number and count all unique occurences
#thus providing a count of alerts

paste zID zDates-day >>  sorted-day
paste zID zDates-hr >>  sorted-hr

#now edit matchedDates so the day is 2 characters wide
	sed -i 's/\<[0-9]\>/0&/' sorted-day
	sed -i 's/\<[0-9]\>/0&/' sorted-hr

y=0 #alert-sensitivity count
#strip out the  trackID from the msgbus.log file
for x in `ls *msgbus.log`; do
	grep -E '"PUBLISH.*Anomaly"' $x | awk -F ',' '{print $7}'| awk -F '\' '{print $3}' | tr -d ':["]' | sort -n > ztrackId

#compare teh sorted_dates, containing trackID and date timestamp with only the trackId from msgbus.log anomaly output
#this will oprovide a date for each trackID that has an anomaly
	awk 'FNR==NR {a[$1]=$0; next}; $1 in a {print a[$1]}' sorted-day ztrackId > zmatchedDates-day
	awk 'FNR==NR {a[$1]=$0; next}; $1 in a {print a[$1]}' sorted-hr ztrackId > zmatchedDates-hr

#stip out only the year month and day for day and  moth day and hour for hour
	awk '{print $2}' zmatchedDates-day > ztmpMatch-day
	awk '{print $2$3$4}' zmatchedDates-hr > ztmpMatch-hr

#sort uniquely giving alerts per day count
	less  ztmpMatch-day | uniq -c > alerts-per-day$y
	less  ztmpMatch-hr | uniq -c > alerts-per-hour$y
	let y=y+1
done
#rm z*

#gnuplot /home/acox/Documents/LinktoDocs/2_work/TESTING/DirectInjectionTesting/sensitivity_plots_per_day


