#!/bin/bash
cd '/home/acox/LONO/micro'

grep  "foundation-video" top.log.1.0.2.57 | awk '{print $10}' > zvid
#grep  "foundation-video" top/top.log.1.0.2.51 | awk '{print $10}' > zvid1
#grep  "foundation-video" top/top.log.1.0.2.46 | awk '{print $10}' > zvid2
#grep  "foundation-video" top/top.log.1.0.2.42 | awk '{print $10}' > zvid3
#grep  "foundation-video" top/top.log.2.0.0.71 | awk '{print $10}' > zvid4

#grep %Cpu top.1.0.2.55-take2 | awk '{print $2}' > zsystem_CPU
#grep "video-source" top.log | awk '{a+=$9} END{print a/NR}' > zsourceCPU
#grep "video-source" top.1.0.2.55-take2 | awk '{a+=$9}NR%10==0{print a;a=0}' > zsourceCPU
#print all CPU used in top.log for vid-src and sum each group of 50 sensors.
#grep "load average" top.1.0.2.55-take2 | awk '{print $12}' > zsystem_load
#grep "KiB Mem" top.1.0.2.55-take2 | awk '{print $8}' > zsystem_mem_used
#grep foundation-vid top.1.0.2.55-take2| awk '{print $9, $10}' > zvideo0
#grep foundation-lea top.1.0.2.55-take2 | awk '{print $9, $10}' > zlearning
#grep foundation-con top.1.0.2.55-take2 | awk '{print $9, $10}' > zcontroller

#sed -n '/GPU /,+3p' micro.nvidia.log | grep GPU| grep -v "GPU Utilization"  > zGPU # gets the GPU card number
#sed -n '/GPU /,+4p' micro.nvidia.log | grep Used > zUsed # memory usage
#sed -n '/GPU /,+4p' micro.nvidia.log | grep Free > zFree
#sed -n '/Utilization/,+4p' micro.nvidia.log | grep -v "Samples" | grep Gpu > zUGpu
#sed -n '/Utilization/,+4p' micro.nvidia.log | grep -v "Samples" | grep Memory > zUMem
#sed -n '/Utilization/,+4p' micro.nvidia.log | grep -v "Samples" | grep Encoder > zUEnc
#sed -n '/Utilization/,+4p' micro.nvidia.log | grep -v "Samples" | grep Decoder > zUDec
#paste zGPU zUsed > zall
#paste zGPU zFree > zallF
#paste zGPU zUGpu > zUtilGpu
#paste zGPU zUMem > zUtilMem
#paste zGPU zUEnc > zUtilEnc
#paste zGPU zUDec > zUtilDec

#EARTH
#grep 0000:04:00.0 zall > zGPU0
#grep 0000:04:00.0 zallF > zGPU0F
#grep 0000:04:00.0 zUtilGpu > zUGpu0
#grep 0000:04:00.0 zUtilMem > zUMem0
#grep 0000:04:00.0 zUtilEnc > zUEnc0
#grep 0000:04:00.0 zUtilDec > zUDec0


#odin
#grep 0000:03:00.0 zall > zGPU0
#grep 0000:03:00.0 zallF > zGPU0F
#grep 0000:03:00.0 zUtilGpu > zUGpu0
#grep 0000:03:00.0 zUtilMem > zUMem0
#grep 0000:03:00.0 zUtilEnc > zUEnc0
#grep 0000:03:00.0 zUtilDec > zUDec0
#grep 0000:84:00.0 zall > zGPU1
#grep 0000:84:00.0 zallF > zGPU1F
#grep 0000:84:00.0 zUtilGpu > zUGpu1
#grep 0000:84:00.0 zUtilMem > zUMem1
#grep 0000:84:00.0 zUtilEnc > zUEnc1
#grep 0000:84:00.0 zUtilDec > zUDec1

#micro
#grep 0000:02:00.0 zall > zGPU0
#grep 0000:02:00.0 zallF > zGPU0F
#grep 0000:02:00.0 zUtilGpu > zUGpu0
#grep 0000:02:00.0 zUtilMem > zUMem0
#grep 0000:02:00.0 zUtilEnc > zUEnc0
#grep 0000:02:00.0 zUtilDec > zUDec0
#grep 0000:03:00.0 zall > zGPU1
#grep 0000:03:00.0 zallF > zGPU1F
#grep 0000:03:00.0 zUtilGpu > zUGpu1
#grep 0000:03:00.0 zUtilMem > zUMem1
#grep 0000:03:00.0 zUtilEnc > zUEnc1
#grep 0000:03:00.0 zUtilDec > zUDec1

gnuplot /home/acox/LONO/plotVidMem
rm z*


